resolver: lts-13.8

packages:
  - .
  - deps/crucible/crucible
  - deps/crucible/what4
  - deps/llvm-pretty
  - deps/llvm-pretty-bc-parser
  - deps/parameterized-utils
  - deps/dwarf
  - deps/elf-edit
  - deps/flexdis86
  - deps/flexdis86/binary-symbols
  - deps/macaw/base
  - deps/macaw/x86

extra-deps:
  - yaml-0.10.0
  - monadLib-3.7.3
  - panic-0.4.0.1
  - fgl-visualize-0.1.0.1
  - dotgen-0.4.2
