sudo: false

dist: bionic

language:  minimal

git:
  submodules: false  # whether to recursively clone submodules

cache:
  directories:
    - $HOME/.stack

before_install:
  # Download and unpack the stack executable
  - mkdir -p $HOME/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

  # This is an unfortunate hack that changes ssh paths into http path, so that
  # we can do a read-only clone of our submodules without worrying about ssh
  # keys.
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init

  # for lean4
  - sudo apt install -y llvm-8
  - sudo apt install -y ninja-build

install:
  - pushd haskell-proto
  # Setup GHC using stack
  - travis_wait stack --stack-yaml stack.yaml setup
  # Build stackage now, so that during the script phase we only see the project build.
  - stack --stack-yaml stack.yaml build --haddock --dependencies-only reopt-vcg
  - popd

  # Setup elan so we can use it to install lean
  - curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf > elan-init.sh
  - chmod a+x elan-init.sh
  - ./elan-init.sh -y
  - source $HOME/.elan/env
  - elan install 3.4.1

  # Install lean4
  - ./scripts/build-lean4.sh lean4/deps/lean4 build/lean4 local
  
# Here starts the actual work to be performed for the package under test;
# any command which exits with a non-zero exit code causes the build to fail.
script:
  # First, build/test the lean code
  - pushd lean/deps/decodex86
  - leanpkg build
  - leanpkg test
  - popd

  - pushd lean
  - leanpkg build
  - leanpkg test
  - popd

  # Build the semantics binary
  - pushd lean4
  - make LEAN=$PWD/../local/bin/lean LEANC=$PWD/../local/bin/leanc LLVM_CONFIG=llvm-config-8
  - popd

  # Now go into the haskell-proto directory to test the Haskell side of things
  - pushd haskell-proto
  - stack --stack-yaml stack.yaml build --haddock reopt-vcg
  - stack --stack-yaml stack.yaml test  reopt-vcg
  - popd
  