HERE := $(realpath $(dir $(realpath $(lastword $(MAKEFILE_LIST)))))
LOCALFILES := AnnotationParsing.lean\
 Hex.lean\
 JsonRoundtrip.lean\
 LoadElf.lean\
 SExp.lean\
 SMTExport.lean
LEANFILES += $(patsubst %,${HERE}/%,${LOCALFILES})
LEAN_PATH := ${LEAN_PATH}:Test=${HERE}
