HERE := $(realpath $(dir $(realpath $(lastword $(MAKEFILE_LIST)))))
LOCALFILES := JsonRoundtrip.lean\
 LoadElf.lean\
 SExp.lean
LEANFILES += $(patsubst %,${HERE}/%,${LOCALFILES})
LEAN_PATH := ${LEAN_PATH}:Test=${HERE}
