
HERE := $(realpath $(dir $(realpath $(lastword $(MAKEFILE_LIST)))))
LOCALFILES := Elf.lean Runelf.lean Translate.lean
LEANFILES += $(patsubst %,${HERE}/%,${LOCALFILES})
LEAN_PATH := ${LEAN_PATH}:Main=${HERE}

