
HERE := $(realpath $(dir $(realpath $(lastword $(MAKEFILE_LIST)))))
LOCALFILES := Annotations.lean\
 ReoptVCG.lean
LEANFILES += $(patsubst %,${HERE}/%,${LOCALFILES})
LEAN_PATH := ${LEAN_PATH}:ReoptVCG=${HERE}

