
HERE := $(realpath $(dir $(realpath $(lastword $(MAKEFILE_LIST)))))
LOCALFILES := Annotations.lean\
 LoadLLVM.lean\
 MCStdLib.lean\
 ReoptVCG.lean\
 SMT.lean\
 SMTParser.lean\
 Types.lean\
 VCGBackend.lean\
 VCGBlock.lean\
 WordSize.lean

LEANFILES += $(patsubst %,${HERE}/%,${LOCALFILES})
LEAN_PATH := ${LEAN_PATH}:ReoptVCG=${HERE}

