[package]
name = "reopt_vcg"
version = "0.1"
lean_version = "3.4.1"
path="src"

[dependencies]
galois_stdlib = { path = "deps/galois_stdlib" }
typed_smt2    = { path = "deps/typed_smt2" }
decodex86     = { path = "../decodex86/" }
