[package]
name = "reopt_vcg"
version = "0.1"
lean_version = "3.4.1"
path="src"

[dependencies]
decodex86     = { path = "deps/decodex86/" }
typed_smt2    = { path = "deps/typed_smt2" }
x86_semantics = { path = "deps/x86_semantics" }
