name: reopt-vcg CI

on:
  push:
    branches: [ master, actions/* ]
  pull_request:
    branches: [ master ]

jobs:
  
  # Build lean4 and cache the result for future jobs
  lean:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    outputs:
      lean4-sha: ${{ steps.version.outputs.lean4-sha }}
        
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - id: version
        run: .github/ci.sh lean4-sha
          
      - uses: actions/cache@v2
        id: lean4-cache
        name: lean4 cache
        path: opt/lean
        key: lean4-${{ runner.os }}-${{ steps.version.outputs.lean4-sha }}

      - name: Compile lean4
         if: steps.lean4-cache.outputs.cache-hit != 'true'
         run: .github/ci.sh lean4-build

  build:
    runs-on: ${{ matrix.os }}
    needs: [lean]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: true

      - uses: actions/cache@v2
        id: lean4-cache
        name: lean4 cache
        path: opt/lean
        key: lean4-${{ runner.os }}-${{ needs.lean.outputs.lean4-sha }}

      - shell: bash
        run: .github/ci.sh build

