name: reopt-vcg CI

on:
  push:
    branches: [ master, actions/* ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - shell: bash
        run: sudo apt-get install clang

      - shell: bash
        run: ./build.sh

      - shell: bash
        run: .github/ci.sh run-tests
